# Generated by Django 5.1.5 on 2025-02-07 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 18, 3, 22, 820060, tzinfo=datetime.timezone.utc)),
        ),
    ]
