# Generated by Django 5.1.5 on 2025-02-08 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usertoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 6, 34, 19, 357117, tzinfo=datetime.timezone.utc)),
        ),
    ]
