# Generated by Django 5.1.5 on 2025-02-08 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usertoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 7, 39, 55, 713671, tzinfo=datetime.timezone.utc)),
        ),
    ]
