# Generated by Django 5.1.5 on 2025-02-08 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usertoken_expires_at_alter_usertoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 10, 32, 8, 449958, tzinfo=datetime.timezone.utc)),
        ),
    ]
