# Generated by Django 5.1.5 on 2025-02-08 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usertoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 13, 25, 13, 122738, tzinfo=datetime.timezone.utc)),
        ),
    ]
